variables:
  ANDROID_COMPILE_SDK: '25'
  ANDROID_BUILD_TOOLS: '25.0.2'
  ANDROID_SDK_TOOLS: '25.2.5'
  SDK: 'android-sdk-linux'
  # Git settings
  # fetch is faster than clone
  GIT_STRATEGY: 'fetch'

cache:
  paths:
    - android-sdk-linux/
    - android-sdk.zip
    - node_modules/
    - docs/node_modules/

before_script:
  # Download tools only if they have not been downloaded yet
  - if [ ! -f android-sdk.zip ]; then
      wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/tools_r${ANDROID_SDK_TOOLS}-linux.zip;
    fi
  # Extract only if the file has never been exracted
  - if [ ! -d android-sdk-linux ]; then
      unzip -qq android-sdk.zip -d $SDK;
    fi
  # Install if not installed
  - if [ ! -d "$SDK/platforms/android-$ANDROID_COMPILE_SDK" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_COMPILE_SDK};
    fi
  - if [ ! -d "$SDK/build-tools/$ANDROID_BUILD_TOOLS" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS};
    fi
  - if [ ! -d "$SDK/extras/android/m2repository" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter extra-android-m2repository;
    fi
  # Export variables for building
  - export ANDROID_HOME=$PWD/$SDK
  - export PATH=$PATH:$PWD/$SDK/platform-tools/
  # Make gradlew executable
  - chmod +x ./gradlew
  # Setup dependencies for documentation
  - cd docs
  - gitbook install
  - cd ..

stages:
  - doc
  - gradle
  - deploy

build:
  stage: gradle
  allow_failure: true
  # Do not download any artifacts
  dependencies: []
  # Do not execute if the branch name contains the word 'doc'
  except:
    - /doc/
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: gradle
  # Do not download any artifacts
  dependencies: []
  # Do not execute if the branch name contains the word 'doc'
  except:
    - /doc/
  script:
    - ./gradlew test

pages:
  stage: doc
  # Do not download any artifacts
  dependencies: []
  # Only execute on branches containing the word 'doc'
  only:
    - /doc/
  script:
    - gitbook build docs public
  artifacts:
    paths:
      - public
  only:
    - master

deploy_app:
  stage: deploy
  only:
    - branches
  except:
    - /doc/
  environment:
    name: app/$CI_COMMIT_REF_NAME
  script:
    - echo "Deploying application to app/$CI_COMMIT_REF_NAME"

deploy_doc:
  stage: deploy
  only:
    - branches
    - /doc/
  environment:
    name: doc/$CI_COMMIT_REF_NAME
  script:
    - echo "Deploying doc to doc/$CI_COMMIT_REF_NAME"
