variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ANDROID_SDK_TOOLS: "25.2.5"
  SDK: "android-sdk-linux"

cache:
  paths:
    - android-sdk-linux/
    - android-sdk.zip
    - node_modules/
    - docs/node_modules/

before_script:
  # Download tools only if they have not been downloaded yet
  - if [ ! -f android-sdk.zip ]; then
      wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/tools_r${ANDROID_SDK_TOOLS}-linux.zip;
    fi
  # Extract only if the file has never been exracted
  - if [ ! -d android-sdk-linux ]; then
      unzip -qq android-sdk.zip -d $SDK;
    fi
  # Install if not installed
  - if [ ! -d "$SDK/platforms/android-$ANDROID_COMPILE_SDK" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_COMPILE_SDK};
    fi
  - if [ ! -d "$SDK/build-tools/$ANDROID_BUILD_TOOLS" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS};
    fi
  - if [ ! -d "$SDK/extras/android/m2repository" ]; then
      echo y | $SDK/tools/android --silent update sdk --no-ui --all --filter extra-android-m2repository;
    fi
  # Export variables for building
  - export ANDROID_HOME=$PWD/$SDK
  - export PATH=$PATH:$PWD/$SDK/platform-tools/
  # Make gradlew executable
  - chmod +x ./gradlew
  # Setup dependencies for documentation
  - cd docs
  - gitbook install
  - cd ..

stages:
  - doc
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

pages:
  stage: doc
  script:
    - gitbook build docs public
  artifacts:
    paths:
      - public
  only:
    - master
